### ISSUE TITLE
Primary Keys

### ISSUE THREAD

**Issue by jenniferliddle** [wtsi-npg/ml_warehouse#17]
I can't help noticing that we have primary keys called "id_flgen_plate_tmp", "id_sample_tmp", "id_study_tmp" and "id_study_users_tmp".

Why are they "tmp"? How long do we expect them to last? When will we get proper permanent keys?

**Comment by mgcam** [comment]
In the absence of obvious columns to join the tables on, these are computed keys that enable quick joins between the tables where the dat afrom different systems are represented. They can be re-computed as records in the tables are changed. This is the main design feature of this database and is not likely to change. The tmp suffix is a hint that these keys are internal to the database and should not be relied on.

The evaluation has been performed and supports the view that this was a good design decision - queries that are meant to be supported are fast.

I believe this issue can now be closed.

**Comment by dkj** [comment]
```_tmp``` is an indicator to downstream users they should not store them or refer to them themselves - other hints such as ```internal``` have failed to do that. ```tmp``` should scare people off storing them - if it doesn't they know from the name what longevity to expect.
