### ISSUE TITLE
run table

### ISSUE THREAD

**Issue by jenniferliddle** [wtsi-npg/ml_warehouse#18]
We have id_run fields in iseq_product_metrics and iseq_run_lane_metrics, and we have a run_status table, but we don't have a run table. This seems very odd. Should there not be a run table, if only to maintain a foreign key constraint between the id_run fields in the other tables and the run_status table? At the moment there is nothing to say that we must have a run_status entry for a particular id_run.

**Comment by mgcam** [comment]
This does not seem to be a problem for queries. This is a warehouse, not a primary source of data. We do not have to copy the whole npg tracking database in the warehouse, just the bare minimum to support queries of interest. To simplify writing the code, the foreigh key constrain is introduced in the DBIx binding.

I believe this issue can now be closed.
