### ISSUE TITLE
users

### ISSUE THREAD

**Issue by jenniferliddle** [wtsi-npg/ml_warehouse#19]
The study_users table has a significant amount of data duplication. The login, email, and name fields need to be normalised into a separate users table.

The role field needs to be moved out into a separate user_role table (or possible a user_role_study table - it isn't clear from the existing structure if the role applies to the user or to the user/study)

**Comment by mgcam** [comment]
This is a warehouse, not the primary  data storage. It is optimised for ease and spead of retrieval for teh purpose of reporting at a cost of some redundancy.

I believe this issues can now be closed.
