### ISSUE TITLE
Foreign Key Constraints

### ISSUE THREAD

**Issue by jenniferliddle** [wtsi-npg/ml_warehouse#20]
Some of the tables have foreign key constraints with the ON DELETE SET NULL and ON DELETE CASCADE attributes. This seems a very dangerous thing to do. In large part it defeats the whole point of have constraints, in that it does not stop somebody from deleting a record they shouldn't, and even worse, it can lead to unwanted side effects.

It is a much more usual practice to *not* delete records in any case, but to have a 'deleted' or 'is_current' flag instead. This helps to maintain an audit trail, especially if an associated status table exists to record when and by whom the record was marked as deleted.

**Comment by mgcam** [comment]
This warehouse is designed to support reporting across multiple systems. It is not primary data storage. It is not meant to be used to audit changes to data, it presents the current snapshot of the data. The cascading on deletes is done when the run_lane metrics for the data is deleted. If there is no lane-level data then it's logical not to have plex data associated with this lane.

Setting foreigh keys to null is done when the flowcell record is deleted. This is an infrequent event. This is usually followed by reanalysis and reloading the metrics. The NULLed foreign key is an indication that something has changed and metrics data have to be reloaded.

I believe this issue can now be closed.

**Comment by dkj** [comment]
By design and fine.
